repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        name: codespell-check
        args: ["--ignore-words=.codespellignore"]
        stages:
          - manual

      - id: codespell
        alias: codespell-fix
        name: codespell-fix
        args:
          - "--ignore-words=.codespellignore"
          - "--write-changes"
        stages:
          - manual

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff
        name: ruff-check
        stages:
          - manual
      - id: ruff
        alias: ruff-check-fix
        name: ruff-check-fix
        args:
          - --fix
        stages:
          - manual
      - id: ruff-format
        name: ruff-format
        stages:
          - manual

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        name: mdformat
        stages:
          - manual

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.15.0
    hooks:
      - id: markdownlint-cli2
        files: '\.(md|markdown)$'
        args: ["--config", ".markdownlint-cli2.yaml"]
        stages:
          - manual
